name: Deploy to VK Apps

'on':
  push:
    tags:
      - '*'
jobs:
  production_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: VK deploy
        run: npm run deploy
